name: cron

on:
  #push:
  schedule:
    - cron: '0 0 * * *' #UTC

jobs:
  cron:
    name: cron
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup PHP, with composer and extensions
        uses: shivammathur/setup-php@v2 #https://github.com/shivammathur/setup-php
        with:
          php-version: 8.4
          coverage: none
      - name: Install Composer dependencies
        run: composer install --no-dev -q
      - name: Run
        run: php artisan inspire
